language: erlang

sudo: required

services:
  - docker

before_install:
  - git clone https://github.com/erlang/rebar3.git; cd rebar3; ./bootstrap; sudo mv rebar3 /usr/local/bin/; cd ..
  - sudo docker info

notifications:
  email: false

otp_release:
  - 21.0

script:
  - make vsn-check
  - make xref
  - make edoc
  - make test-env
  - make t
  - make coveralls
  - make cover

